#!/usr/bin/env python3
import os
import sys

from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @username")
        
    get_tweets = get_user_timeline(sys.argv[1], 50)
    if get_tweets == None:
        sys.exit("Not able to retrieve tweets from user")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in get_tweets:
        # analyze word
        score = analyzer.analyze(tweet)
        print(score)
        if score > 0:
            print(colored(":)", "green"), end=" ")
        elif score < 0:
            print(colored(":(", "red"), end=" ")
        else:
            print(colored(":|", "yellow"), end=" ")
        
if __name__ == "__main__":
    main()
    
